//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cybershopnew.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cygnewEntities1 : DbContext
    {
        public cygnewEntities1()
            : base("name=cygnewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookstable> bookstables { get; set; }
        public virtual DbSet<mobilestable> mobilestables { get; set; }
        public virtual DbSet<accessory> accessories { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<clothingtable> clothingtables { get; set; }
    }
}
